### ISSUE TITLE
Pipe error when turning off/on socket in Python 2.7.15

### ISSUE THREAD

**Issue by JayStringer** [xypron/pysispm#1]
Hey, I'm not sure if Python 2.7.x is supported but I'm having issues turning off/on sockets while it works perfectly in python 3.6.7. Running a very simple script to just turn one of the sockets on gives me this:

```
Traceback (most recent call last):
  File "test_usb.py", line 95, in <module>
    print(switchon(dev, 3))
  File "test_usb.py", line 91, in switchon
    buf = dev.ctrl_transfer(0x21, 0x09, 0x0300 + 3 * i, 0, buf, 500)
  File "/home/jay/workspace/virtualenvs/sandboxpy2/local/lib/python2.7/site-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/home/jay/workspace/virtualenvs/sandboxpy2/local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/home/jay/workspace/virtualenvs/sandboxpy2/local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```
I'm not having any issues with getting the status of a socket or getting the list of supported devices. Running Pop OS 18.04 which is basically a fork of Ubuntu 18.04.

Thanks in advance.

**Comment by xypron** [comment]
examples/sispmctl.py has this line:

     #!/usr/bin/python3

So when you execute it it will be run via Python 3.

README.rst has this line:

     apt-get install python3-usb

Python 2 will not be maintained after December 31st, 2019. So I do not plan any backporting.

**Comment by JayStringer** [comment]
Ok, thank you for getting back to me :)

**Comment by xypron** [comment]
A similar issue with Python 3.5 has been reported in #4, #5
